import os

DEBUG = True
SECRET_KEY = 'development key'
BABEL_DEFAULT_LOCALE = 'zh_CN'
BABEL_DEFAULT_TIMEZONE = 'CST'
SQLALCHEMY_DATABASE_URI = os.environ['DATABASE_URL']
SO_AUTO_INCOMING_STATUS_ID = 6
SO_AUTO_INCOMING_CATEGORY_ID = 9
SO_AUTO_EXPENSE_STATUS_ID = 10
SO_AUTO_EXPENSE_CATEGORY_ID = 11
PO_AUTO_GOODS_EXPENSE_STATUS_ID = 10
PO_AUTO_GOODS_EXPENSE_CATEGORY_ID = 12
PO_AUTO_LOGISTIC_EXPENSE_STATUS_ID = 10
PO_AUTO_LOGISTIC_EXPENSE_CATEGORY_ID = 13
