import os


BABEL_DEFAULT_LOCALE = 'zh_CN'
BABEL_DEFAULT_TIMEZONE = 'CST'
SQLALCHEMY_ECHO = False
SQLALCHEMY_DATABASE_URI = os.environ['DATABASE_URL']
SECRET_KEY = '123QWEasDzXcqazw'
SECURITY_PASSWORD_HASH = 'pbkdf2_sha512'
SECURITY_PASSWORD_SALT = '123QWEasDzXcqazw'
SECURITY_REGISTERABLE = False
SECURITY_CONFIRMABLE = False
SECURITY_RECOVERABLE = False
SECURITY_CHANGEABLE = False
DEBUG = (os.environ.get('DEBUG') == "True")
