import os

DEBUG = True
SECRET_KEY = 'development key'
BABEL_DEFAULT_LOCALE = 'zh_CN'
BABEL_DEFAULT_TIMEZONE = 'CST'
SQLALCHEMY_DATABASE_URI = os.environ['DATABASE_URL']
AUTO_INCOMING_STATUS_ID=6
AUTO_INCOMING_CATEGORY_ID=9
AUTO_EXPENSE_STATUS_ID=10
AUTO_EXPENSE_CATEGORY_ID=11