# PO status definition
PO_STATUS_KEY = u'PURCHASE_ORDER_STATUS'
PO_RECEIVED_STATUS_KEY = u'PURCHASE_ORDER_RECEIVED'
PO_PART_RECEIVED_STATUS_KEY = u'PURCHASE_ORDER_PART_RECEIVED'
PO_DRAFT_STATUS_KEY = u'PURCHASE_ORDER_DRAFT'
PO_ISSUED_STATUS_KEY = u'PURCHASE_ORDER_ISSUED'

# Inventory transaction status definition
PURCHASE_IN_INV_TRANS_KEY = u'PURCHASE_IN'
SALES_OUT_INV_TRANS_TYPE_KEY = u'SALES_OUT'

# Inventory transaction type definition
INVENTORY_TRANSACTION_TYPE_KEY = u'INVENTORY_TRANSACTION_TYPE'

# Receiving status definition
RECEIVING_DRAFT_STATUS_KEY = u'RECEIVING_DRAFT'
RECEIVING_COMPLETE_STATUS_KEY = u'RECEIVING_COMPLETE'

# Shipping status definition
SHIPPING_STATUS_KEY = u'SHIPPING_STATUS'

# Expense status and type definition key
EXP_TYPE_KEY = u'EXP_TYPE'
EXP_STATUS_KEY = u'EXP_STATUS'

# Incoming status and type definition key
INCOMING_TYPE_KEY = u'INCOMING_TYPE'
INCOMING_STATUS_KEY = u'INCOMING_STATUS'


