# PO status definition
PO_STATUS_KEY = u'PURCHASE_ORDER_STATUS'
PO_RECEIVED_STATUS_KEY = u'PURCHASE_ORDER_RECEIVED'
PO_SHIPPED_STATUS_KEY = u'PURCHASE_ORDER_SHIPPED_OUT'
PO_PART_RECEIVED_STATUS_KEY = u'PURCHASE_ORDER_PART_RECEIVED'
PO_DRAFT_STATUS_KEY = u'PURCHASE_ORDER_DRAFT'
PO_ISSUED_STATUS_KEY = u'PURCHASE_ORDER_ISSUED'

# PO type key
PO_TYPE_KEY = u'PURCHASE_ORDER_TYPE'
DIRECT_PO_TYPE_KEY = u'DIRECT_PURCHASE_ORDER'
FRANCHISE_PO_TYPE_KEY = u'FRANCHISE_PURCHASE_ORDER'

# SO type key
SO_TYPE_KEY = u'SALES_ORDER_TYPE'
DIRECT_SO_TYPE_KEY = u'DIRECT_SALES_ORDER'
FRANCHISE_SO_TYPE_KEY = u'FRANCHISE_SALES_ORDER'

# SO Status key
SO_STATUS_KEY = u'SALES_ORDER_STATUS'
SO_CREATED_STATUS_KEY = u'SALES_ORDER_CREATED'
SO_SHIPPED_STATUS_KEY = u'SALES_ORDER_SHIPPED'
SO_DELIVERED_STATUS_KEY = u'SALES_ORDER_DELIVERED'

# Inventory transaction type definition key
PURCHASE_IN_INV_TRANS_KEY = u'PURCHASE_IN'
SALES_OUT_INV_TRANS_TYPE_KEY = u'DIRECT_SALES_OUT'

# Inventory transaction type definition
INVENTORY_TRANSACTION_TYPE_KEY = u'INVENTORY_TRANSACTION_TYPE'
INVENTORY_DAMAGED_TYPE_KEY = u'INVENTORY_DAMAGED'
INVENTORY_LOST_TYPE_KEY = u'INVENTORY_LOST'

# Receiving status definition
RECEIVING_STATUS_KEY = u'RECEIVING_STATUS'
RECEIVING_DRAFT_STATUS_KEY = u'RECEIVING_DRAFT'
RECEIVING_COMPLETE_STATUS_KEY = u'RECEIVING_COMPLETE'

# Shipping status definition
SHIPPING_STATUS_KEY = u'SHIPPING_STATUS'
SHIPPING_COMPLETE_STATUS_KEY = 'SHIPPING_COMPLETE'


# Expense status and type definition key
EXP_TYPE_KEY = u'EXP_TYPE'
EXP_STATUS_KEY = u'EXP_STATUS'

# Incoming status and type definition key
INCOMING_TYPE_KEY = u'INCOMING_TYPE'
INCOMING_STATUS_KEY = u'INCOMING_STATUS'

# Shipping complete status key
SHIPPING_COMPLETE_STATUS_KEY = u'SHIPPING_COMPLETE'

# Customer related enum value keys
CUSTOMER_JOIN_CHANNEL_KEY = u'CUSTOMER_JOIN_CHANNEL'
CUSTOMER_LEVEL_KEY = u'CUSTOMER_LEVEL'

# User locale settings
LANGUAGE_VALUES_KEY = u'LANGUAGES'
TIMEZONE_VALUES_KEY = u'TIMEZONES'

# Super admin role
SUPER_ADMIN_ROLE_NAME = u'super_admin'

# Organization type key
ORGANIZATION_TYPE_KEY = u'ORGANIZATION_TYPE'
DIRECT_SELLING_STORE_ORG_TYPE_KEY = u'DIRECT_SELLING_STORE'
FRANCHISE_STORE_ORG_TYPE_KEY = u'FRANCHISE_STORE'

# Related type
FRANCHISE_PO_TO_SO_RT_KEY = u'FRANCHISE_PO_TO_SO'
