# PO status definition
PO_STATUS_KEY = u'PURCHASE_ORDER_STATUS'
PO_RECEIVED_STATUS_KEY = u'PURCHASE_ORDER_RECEIVED'
PO_PART_RECEIVED_STATUS_KEY = u'PURCHASE_ORDER_PART_RECEIVED'
PO_DRAFT_STATUS_KEY = u'PURCHASE_ORDER_DRAFT'
PO_ISSUED_STATUS_KEY = u'PURCHASE_ORDER_ISSUED'

# Inventory transaction type definition key
PURCHASE_IN_INV_TRANS_KEY = u'PURCHASE_IN'
SALES_OUT_INV_TRANS_TYPE_KEY = u'SALES_OUT'

# Inventory transaction type definition
INVENTORY_TRANSACTION_TYPE_KEY = u'INVENTORY_TRANSACTION_TYPE'
INVENTORY_DAMAGED_TYPE_KEY = u'INVENTORY_DAMAGED'
INVENTORY_LOST_TYPE_KEY = u'INVENTORY_LOST'

# Receiving status definition
RECEIVING_STATUS_KEY = u'RECEIVING_STATUS'
RECEIVING_DRAFT_STATUS_KEY = u'RECEIVING_DRAFT'
RECEIVING_COMPLETE_STATUS_KEY = u'RECEIVING_COMPLETE'

# Shipping status definition
SHIPPING_STATUS_KEY = u'SHIPPING_STATUS'

# Expense status and type definition key
EXP_TYPE_KEY = u'EXP_TYPE'
EXP_STATUS_KEY = u'EXP_STATUS'

# Incoming status and type definition key
INCOMING_TYPE_KEY = u'INCOMING_TYPE'
INCOMING_STATUS_KEY = u'INCOMING_STATUS'

# Shipping complete status key
SHIPPING_COMPLETE_STATUS_KEY = u'SHIPPING_COMPLETE'

# Customer related enum value keys
CUSTOMER_JOIN_CHANNEL_KEY = u'CUSTOMER_JOIN_CHANNEL'
CUSTOMER_LEVEL_KEY = u'CUSTOMER_LEVEL'

# User locale settings
LANGUAGE_VALUES_KEY = u'LANGUAGES'
TIMEZONE_VALUES_KEY = u'TIMEZONES'

# Super admin role
SUPER_ADMIN_ROLE_NAME = u'super_admin'

# Organization type key
ORGANIZATION_TYPE_KEY = u'ORGANIZATION_TYPE'
