""" Add language and time zone to user profile

Revision ID: 736f035d9c77
Revises: d0bbf6c460f5
Create Date: 2016-03-04 20:37:33.149292

"""

# revision identifiers, used by Alembic.
revision = '736f035d9c77'
down_revision = 'd0bbf6c460f5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('locale_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('timezone_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'enum_values', ['timezone_id'], ['id'])
    op.create_foreign_key(None, 'user', 'enum_values', ['locale_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'timezone_id')
    op.drop_column('user', 'locale_id')
    ### end Alembic commands ###
