"""Change role to a parent-children relationship

Revision ID: d5ec1187aad4
Revises: 736f035d9c77
Create Date: 2016-03-08 15:01:11.529734

"""

# revision identifiers, used by Alembic.
revision = 'd5ec1187aad4'
down_revision = '736f035d9c77'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'role', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'role', 'role', ['parent_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role', type_='foreignkey')
    op.drop_column(u'role', 'parent_id')
    ### end Alembic commands ###
