"""Add status column to purchase order.

Revision ID: 2673ce30fb12
Revises: 1b3411739b82
Create Date: 2015-07-07 23:00:32.912611

"""

# revision identifiers, used by Alembic.
revision = '2673ce30fb12'
down_revision = '1b3411739b82'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_order', sa.Column('status_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'purchase_order', 'enum_values', ['status_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchase_order', type_='foreignkey')
    op.drop_column('purchase_order', 'status_id')
    ### end Alembic commands ###
