# encoding=utf-8
"""Add type to organization and franchise price to product

Revision ID: 7868d8cd502d
Revises: 0051eed6ee5d
Create Date: 2016-07-22 21:36:05.852282

"""

# revision identifiers, used by Alembic.
revision = '7868d8cd502d'
down_revision = '0051eed6ee5d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.sql import text
    op.add_column('organization', sa.Column('type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'organization', 'enum_values', ['type_id'], ['id'])
    op.add_column('product', sa.Column('franchise_price', sa.Numeric(precision=8, scale=2, decimal_return_scale=2), nullable=True))
    op.get_bind().execute(text("INSERT INTO enum_values (type_id, code, display) VALUES (1, 'ORGANIZATION_TYPE', '组织类型');"))
    op.get_bind().execute(text("INSERT INTO enum_values (type_id, code, display) VALUES ((SELECT id FROM enum_values WHERE code='ORGANIZATION_TYPE'), 'DIRECT_SELLING_STORE', '直营店');"))
    op.get_bind().execute(text("INSERT INTO enum_values (type_id, code, display) VALUES ((SELECT id FROM enum_values WHERE code='ORGANIZATION_TYPE'), 'FRANCHISE_STORE', '加盟店');"))
    op.get_bind().execute(text("UPDATE organization set type_id = (SELECT id FROM enum_values WHERE code='DIRECT_SELLING_STORE')"))
    op.get_bind().execute(text("ALTER TABLE organization ALTER COLUMN type_id SET NOT NULL;"))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.sql import text
    op.get_bind().execute(text("DELETE FROM enum_values where code in ('ORGANIZATION_TYPE', 'DIRECT_SELLING_STORE', 'FRANCHISE_STORE')"))
    op.drop_column('product', 'franchise_price')
    op.drop_constraint(None, 'organization', type_='foreignkey')
    op.drop_column('organization', 'type_id')
    ### end Alembic commands ###
