"""Add related values table

Revision ID: 668c5802ed96
Revises: db9ee0625c86
Create Date: 2016-09-09 13:14:32.786613

"""

# revision identifiers, used by Alembic.
revision = '668c5802ed96'
down_revision = 'db9ee0625c86'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('related_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_object_id', sa.Integer(), nullable=False),
    sa.Column('from_object_type', sa.Text(), nullable=False),
    sa.Column('to_object_id', sa.Integer(), nullable=False),
    sa.Column('to_object_type', sa.Text(), nullable=False),
    sa.Column('relation_type_id', sa.Integer(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['relation_type_id'], ['enum_values.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('related_values')
    ### end Alembic commands ###
