"""Change attribute lead day and deliver day in product to required.

Revision ID: 428a1c2e88b2
Revises: 5590114aa058
Create Date: 2015-07-26 14:12:35.177582

"""

# revision identifiers, used by Alembic.
revision = '428a1c2e88b2'
down_revision = '5590114aa058'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE product SET lead_day ='3' WHERE lead_day IS NULL")
    op.execute("UPDATE product SET deliver_day ='3' WHERE deliver_day IS NULL")
    op.alter_column('product', 'deliver_day', existing_type=sa.INTEGER(), nullable=False)
    op.alter_column('product', 'lead_day', existing_type=sa.INTEGER(), nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'lead_day', existing_type=sa.INTEGER(), nullable=True)
    op.alter_column('product', 'deliver_day', existing_type=sa.INTEGER(), nullable=True)
    ### end Alembic commands ###
