# coding=utf-8
"""Add need advice setting on production level, add external_id on sales order line

Revision ID: faa0a5506a14
Revises: 38571f2c12fc
Create Date: 2016-02-04 15:55:19.050763

"""

# revision identifiers, used by Alembic.
revision = 'faa0a5506a14'
down_revision = '38571f2c12fc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('need_advice', sa.Boolean(), nullable=True))
    op.add_column('sales_order_line', sa.Column('external_id', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_order_line', 'external_id')
    op.drop_column('product', 'need_advice')
    ### end Alembic commands ###
