# coding=utf-8
"""Add invalid SO status and rejected PO status.

Revision ID: 5751ca3c5091
Revises: 2a4243d9cd8c
Create Date: 2017-01-10 11:01:15.389663

"""

# revision identifiers, used by Alembic.
from sqlalchemy import text

revision = '5751ca3c5091'
down_revision = '2a4243d9cd8c'

from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.get_bind().execute(text("INSERT INTO enum_values (type_id, code, display) values ((SELECT id FROM enum_values WHERE code='SALES_ORDER_STATUS'), 'SALES_ORDER_INVALID', '无效');"))
    op.get_bind().execute(text("INSERT INTO enum_values (type_id, code, display) values ((SELECT id FROM enum_values WHERE code='PURCHASE_ORDER_STATUS'), 'PURCHASE_ORDER_REJECTED', '被拒绝');"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.get_bind().execute(text("DELETE FROM enum_values where code = 'SALES_ORDER_INVALID'"))
    op.get_bind().execute(text("DELETE FROM enum_values where code = 'PURCHASE_ORDER_REJECTED'"))
    # ### end Alembic commands ###
