""" Add role for report view

Revision ID: 5fa54f2ce13c
Revises: 5751ca3c5091
Create Date: 2017-03-05 15:53:41.233842

"""

# revision identifiers, used by Alembic.
revision = '5fa54f2ce13c'
down_revision = '5751ca3c5091'

from alembic import op
import sqlalchemy as sa

from sqlalchemy import text

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.get_bind().execute(text("INSERT INTO role (name, description) VALUES ('report_view', 'View Reports');"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.get_bind().execute(text("DELETE FROM ROLE WHERE name = 'report_view'"))
    # ### end Alembic commands ###
