"""Add role to view supplier sales report

Revision ID: b9dc56c47ef4
Revises: e1f806a716b9
Create Date: 2017-06-07 21:59:35.060786

"""

# revision identifiers, used by Alembic.
revision = 'b9dc56c47ef4'
down_revision = 'e1f806a716b9'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.get_bind().execute(text("insert into role (name, description, is_system) values ('{0}', '{1}', 't')".format('sales_report_view', 'Sales report view')));
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.get_bind().execute(text("delete from roles_users where role_id = (select id from role where name = '{0}')".format('sales_report_view')))
    op.get_bind().execute(text("delete from role where name = '{0}'".format('sales_report_view')));
    # ### end Alembic commands ###
