"""empty message

Revision ID: b98cb7d75318
Revises: 5751ca3c5091
Create Date: 2017-01-18 10:39:36.647708

"""

# revision identifiers, used by Alembic.
revision = 'b98cb7d75318'
down_revision = '5751ca3c5091'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role', 'is_system',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text(u'true'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role', 'is_system',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text(u'true'))
    # ### end Alembic commands ###
